GET http://localhost:8000/batch/test
Accept: application/json

###

GET http://localhost:8003/batch/hello
Accept: application/json

###

GET http://localhost:8003/batch/admin/job/run
content-type: application/json

{
  "name": "com.jiawa.train.batch.job.DailyTrainJob",
  "jobGroupName": "default"
}



