POST http://localhost:8000/member/passenger/register
Content-Type: application/json
token:{{token}}

{
  "name": "test",
  "idCard": "123",
  "type": "1",
  "memberId": "123"
}



###
#测试
GET http://localhost:8001/member/passenger/hello
Content-Type: application/json

###
#错误请求
POST http://localhost:8001/member/passenger/register
Content-Type: application/json

{
  "idCard": "123",
  "type": "1",
  "memberId": "123"
}

###
#通过网关发送请求，需要带上token
POST http://localhost:8001/member/passenger/register
Content-Type: application/json

{
  "idCard": "123",
  "type": "1",
  "memberId": "123"
}

###
POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token:{{token}}

{
  "name": "test3",
  "idCard": "1233121",
  "type": "3"
}

###
GET http://localhost:8000/member/passenger/query-list
Accept: application/json
token:{{token}}


